### ISSUE TITLE
Example Broken on Windows

### ISSUE THREAD

**Issue by t0mdavid-m** [OpenMS/streamlit-template#105]
This example is broken on windows as grep does not exist:

https://github.com/OpenMS/streamlit-template/blame/df9a89af3f5a04dfafe068442a4a4e8a422aa9ff/content/run_subprocess.py#L69

There are multiple solutions here:
- Make a note that this does not work on windows
- Replace this example with an example that works cross-platform
- Detect the os and use `findstr` instead of `grep` if windows is detected

**Comment by Arslan-Siraj** [comment]
Detect the os and use findstr instead of grep if windows is detected. I think this is good solution.

**Comment by Arslan-Siraj** [comment]
https://github.com/OpenMS/streamlit-template/pull/107
