### ISSUE TITLE
Error in Windows packages with latest streamlit 1.30

### ISSUE THREAD

**Issue by axelwalter** [OpenMS/streamlit-template#40]
Github action runs without errors, however opening the app will raise the following error:

![image](https://github.com/OpenMS/streamlit-template/assets/72203175/52398284-cb2a-41ae-beb7-c8ad2dd2c4d1)

The issue seems to be with streamlit version 1.30 (latest), rolling back to 1.29 resolves the issue for now.

The workflow to build should be adopted to 1.30 and perhaps include a test to check if the app launches without errors.

**Comment by timosachsenberg** [comment]
Yeah I think having a test in the action that ensures that the app can be launched is important. +1
