### ISSUE TITLE
Check if server can be deployed on ibmidocker

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/streamlit-template#5]
Axel and me created an initial template for streamlit deployment.
I think we are at a point to test if someone can deploy it on ibmidocker

https://github.com/OpenMS/streamlit-template/pull/4

Steps necessary:
- check out the repo on imbidocker
- build the image
- run docker
- check with IT how to make it accessible from outside (e.g., by adding it to our proxy ibmiservices )

User story: User wants to make his App available.

- User forks https://github.com/OpenMS/streamlit-template and adds his App code to it. Renames his repo to have a meaningful name. E.g., "Cross-Linking-App". If needed, adapts the environment.yml file for additional dependencies.
- User adds his Repo as a submodule to https://github.com/OpenMS/streamlit-deployment
- User adds his App to the local.yml docker compose script (untested), potentially ports need to be adjusted such that there is no overlap between multiple apps

This should allow to deploy multiple streamlit apps on ibmidocker. How we make it accessible through our proxy ibmiservice needs to be discussed with the IT.

**Comment by timosachsenberg** [comment]
I think @JeeH-K and @enetz would be great candidates for that because deploying their tools as web app would profit from that

**Comment by timosachsenberg** [comment]
Happy to explain the plan a bit more in detail once @enetz is back.

**Comment by timosachsenberg** [comment]
I updated #4  to be only Docker based. should make it much easier to build custom docker container for feature branches.

**Comment by JeeH-K** [comment]
Hi Timo

> @enetz and @JeeH-K is it possible to display and browse spectra (e.g., by clicking on table rows of identifications / masses)? I think this would be another important visualization we would need.

Yes, displaying and browsing spectra part is (partially) done in FLASHViewer right now. It has a scan table that interacts with deconvolved spectra. When a row in the scan table is clicked, a deconvolved spectrum and a mass table are drawn/updated.

**Comment by timosachsenberg** [comment]
let's move the web apps forward and meet after this sprint to discuss state/limitations.

**Comment by poshul** [comment]
How is this looking?

**Comment by enetz** [comment]
I have gotten access to ibmidocker from our IT admin just before my vacation. I should be able to set up a streamlit service, that is accessible from the local network, in the next few days.
Making it public (accessible from outside our local network) will require asking the IT admin to set up proxies for each tool with its own port. Which we can do, when the tools are robust enough for external users.

**Comment by poshul** [comment]
Sounds good. Thanks!

**Comment by timosachsenberg** [comment]
If the apache is the proxy server, we can probably do this ourself? Would be good if we find a solution that doesn't require contacting an admin every time

**Comment by enetz** [comment]
This works now in general, one app is running on the local network. 

Two points I will contact the admin about:

1. Can we do the proxy setup ourselves
2. Broader access to the ibmidocker machine for the OpenMS team:
    - give everyone access through their WSI accounts, or
    - make one collective OpenMS WSI account to manage apps? (This option might be less secure, since login info for this WSI account would have to be somewhat public within our core team)

**Comment by timosachsenberg** [comment]
ok that is nice. Thanks! Would be great if you could stay in contact with the admin and push that forward.

**Comment by timosachsenberg** [comment]
any update here?

**Comment by timosachsenberg** [comment]
please meet organize yourself as a "task force"

**Comment by axelwalter** [comment]
Workspaces without activity in the last seven days will be removed via a daily cron job. 

Deployment and updating apps on ibmidocker works. Currently running the template app and UmetaFlow GUI.

**Comment by axelwalter** [comment]
A detailed tutorial how to host apps can be found [here](https://github.com/KohlbacherLab/OpenMS_infrastructure/blob/main/host-openms-streamlit-apps-on-ibmidocker.md).

Template App and UmetaFlow are accessible as abi-services.

https://abi-services.cs.uni-tuebingen.de/streamlit-template/
https://abi-services.cs.uni-tuebingen.de/umetaflow/

**Comment by axelwalter** [comment]
- [ ] add [app testing API](https://docs.streamlit.io/library/api-reference/app-testing) which was recently introduced in streamlit 1.28
