### ISSUE TITLE
Make container smaller

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/streamlit-template#7]
e.g. we don't need the OpenMS source folder any more (it is currently kept because it contains the share/folder).
TODO:

- set the cmake flag -DCMAKE_INSTALL_PREFIX when generating the build system to a folder we want to install OpenMS to

call
- cmake -DCOMPONENT="library" -P build/cmake_install.cmake
- cmake -DCOMPONENT="applications" -P build/cmake_install.cmake
- cmake -DCOMPONENT="share" -P build/cmake_install.cmake

to copy files into that folder

**Comment by timosachsenberg** [comment]
maybe take a look at these base images? https://github.com/nektos/act/blob/master/IMAGES.md

**Comment by poshul** [comment]
Any updates on this?

**Comment by JeeH-K** [comment]
Apologies. Not yet. I had to work on other stuff before Kyowon's holiday. I'll put my time on this part for the next sprint

**Comment by timosachsenberg** [comment]
any update this time?

**Comment by axelwalter** [comment]
In the current Dockerfile source and build directories get deleted, after the required files have been copied to a separate directory `/openms/bin` `/openms/lib` and `/openms/share` and added to PATH.
