### ISSUE TITLE
Evaluate if streamlit app can be packaged as .exe on windows / other platforms

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/streamlit-template#8]
see e.g. https://discuss.streamlit.io/t/using-pyinstaller-or-similar-to-create-an-executable/902/86

would be interesting to check if this is possible e.g., probably similar to building a whl

**Comment by timosachsenberg** [comment]
see also https://www.youtube.com/watch?v=G7Qeg_rbYM8

**Comment by timosachsenberg** [comment]
Another option would be creating a wix installer that installs .net, docker and creates a desktop icon to launch the browser + webserver

**Comment by Arslan-Siraj** [comment]
via pyinstaller
https://github.com/OpenMS/streamlit-template/pull/10

**Comment by Arslan-Siraj** [comment]
looking for how to include docker in .exe file configurations, I see with stlite, a port of Streamlit to WebAssembly powered by Pyodide, + electron.

**Comment by timosachsenberg** [comment]
Did you also check if .exe / falls etc could be integrated into pyinstaller file? E.g. if we decide to just provide desktop versions for windows?

**Comment by Arslan-Siraj** [comment]
https://github.com/Arslan-Siraj/streamlit-template/tree/exe-check/dist have to provide like this for streamlit app, streamlit code + exe. user can run the streamlit app locally (I do for sample OpenMS template). I am just wondering how to integrate docker base app via this approach. It could be possible? or there someway to install pyinstaller inside docker and take .exe image?. If we cannot do via pyinstaller, we have to go for something else like wix installer.

**Comment by Arslan-Siraj** [comment]
I can try.
mistakenly removed from assignee ;)

**Comment by timosachsenberg** [comment]
see also https://github.com/axelwalter/umetaflow-gui/releases/tag/v1.0.0
@axelwalter already had some success with a different approach so would be good to discuss

**Comment by Arslan-Siraj** [comment]
Done, https://github.com/OpenMS/streamlit-template/pull/18
