### ISSUE TITLE
Bug in captcha

### ISSUE THREAD

**Issue by jcharkow** [OpenMS/streamlit-template#93]
When run into the captcha, this can be avoided by navigating to a different tab.

E.g. When you arrive at this page: 
![image](https://github.com/user-attachments/assets/4564fe4f-6e6e-4bfa-9266-ce749e1e9aa5)

If you click any of the sidebar tools you do not have to verify if you are a robot or not.

**Comment by Arslan-Siraj** [comment]
fixing here https://github.com/OpenMS/streamlit-template/pull/95
