### ISSUE TITLE
Only include relevant dependencies

### ISSUE THREAD

**Issue by t0mdavid-m** [OpenMS/streamlit-template#96]
#68 uses the new package as zip routine introduced in https://github.com/OpenMS/OpenMS/pull/7529 to include all dependencies needed for OpenMS in the windows packages. Furthermore, it takes care that only relevant TOPP tools are included in the final zip file.

It would be nice to only include dependencies for the specified TOPP tools in the zip.

**Comment by jpfeuffer** [comment]
From the openms side, the only way of saving dependencies is to build without GUI (since I assume you don't need it) and to not ship every topp tool needed.
Library-wise there is nothing you can save. Everything depends on the monolithic libOpenMS (which also always includes libOpenSwath).
If your goal is to modularize the library, I am all for it! 😉

**Comment by jpfeuffer** [comment]
You can reduce *some* dependencies of dependencies by completely selfbuilding every single dependency (like qt or boost) and disabling optional features like different compression algorithms. But those will be minor savings.

**Comment by t0mdavid-m** [comment]
I was not referring the OpenMS and OpenSwath dll files but with the installer we currently ship around 200 dlls. I was wondering if  there would be a good way to reduce them based on if they are actually needed? 

For WebApps often only a single TOPP tool is needed. My assumption was that not every single TOPP tools needs all of these dependencies? 

I tried building with and without GUI but this only removed a few QT related dependencies.

**Comment by jpfeuffer** [comment]
I think the rest is unfortunately needed. The dependencies are coming from OpenMS.dll and every TOPP Tool depends on this dll. One would need to split up OpenMS to do this. Not impossible and long overdue but also a bit of work.

You could require some dlls to be installed by the user with package managers. But this will be tricky for windows users.

**Comment by t0mdavid-m** [comment]
Ok thanks for the insight! I agree that requiring additional dependencies via package managers would be tricky for windows users (and since we are targeting amateur users with regards to computer literacy it would definitely be too complicated for this purpose).

Since reducing dependencies would require major refactoring of OpenMS, this is out of scope here. Hence, I am closing this issue.
